spring.application.name=Notification-Management

# Server Configuration
server.port=8084

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/HealthCare
spring.data.mongodb.database=HealthCare

# Service URLs
services.patient.base-url=http://localhost:8081
services.doctor.base-url=http://localhost:8082
services.appointment.base-url=http://localhost:8080

# Logging
logging.level.com.Notify.Notification_Management=DEBUG

# Spring Boot Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lasannavodya@gmail.com
spring.mail.password=kgajmpwbgcjquxmv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Infobip SMS Configuration
infobip.api.key=a547cd44c0aa1b457c348b0bcc3b004e-51c25e95-5860-4012-b3ae-4b74fcf12916
infobip.base.url=https://rkpjye.api.infobip.com
infobip.sender.id=HealthCare
